# Generated by Django 4.1 on 2023-11-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('areas_of_interest', models.TextField()),
                ('password', models.TextField()),
                ('display_picture', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
